# Generated by Django 3.1.5 on 2021-01-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Названия сообщества по интересам.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='posts.group', verbose_name='Название сообщества'),
        ),
    ]
